apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "keepalived.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keepalived.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keepalived.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        {{- include "keepalived.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KEEPALIVED_VIRTUAL_IP
              value: {{ .Values.virtualIP }}
            - name: KEEPALIVED_PASSWORD
              value: test
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
