name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "Moritz Weichert"
          git config user.email "moritz@kirstein.me"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"